export const DUMMY_ACTION = 'DUMMY_ACTION';

export const FETCH_LATEST_THREADS = 'FETCH_LATEST_THREADS';
export const CHANGE_LATEST_THREADS = 'CHANGE_LATEST_THREADS';

export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ROUTE_CHANGE_START = 'ROUTE_CHANGE_START';
export const ROUTE_CHANGE_COMPLETE = 'ROUTE_CHANGE_COMPLETE';

export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';

export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const CHANGE_IS_PAGE_LOADING = 'CHANGE_IS_PAGE_LOADING';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const CHANGE_CATEGORIES = 'CHANGE_CATEGORIES';

export const FETCH_THREAD_SINGLE = 'FETCH_THREAD_SINGLE';
export const SET_THREAD_SINGLE = 'SET_THREAD_SINGLE';

export const FETCH_SCORING_CATEGORIES = 'FETCH_SCORING_CATEGORIES';

export const FETCH_THREAD_VOTES = 'FETCH_THREAD_VOTES';
export const FETCH_MESSAGE_VOTES = 'FETCH_MESSAGE_VOTES';
export const FETCH_USER_VOTE = 'FETCH_USER_VOTE';

export const SET_SCORING_CATEGORIES = 'SET_SCORING_CATEGORIES';

export const SET_THREAD_VOTES = 'SET_THREAD_VOTES';
export const SET_MESSAGE_VOTES = 'SET_MESSAGE_VOTES';
export const SET_USER_VOTE = 'SET_USER_VOTE';

export const SCORING_FORM_SUBMIT = 'SCORING_FORM_SUBMIT';

