export const ROUTE_CHANGE_START = 'ROUTE_CHANGE_START';
export const ROUTE_CHANGE_COMPLETE = 'ROUTE_CHANGE_COMPLETE';

export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const RESET_FLASH_MESSAGE = 'RESET_FLASH_MESSAGE';

export const CHANGE_IS_PAGE_LOADING = 'CHANGE_IS_PAGE_LOADING';


