export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_REFRESH_STATUS = 'SET_REFRESH_STATUS';
export const GET_NEW_TOKEN_WITH_REFRESH = 'GET_NEW_TOKEN_WITH_REFRESH';
